### ISSUE TITLE
Release teal and modules in GitHub

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/nestdevs-tasks#13]
### Summary
This is continuation of insightsengineering/teal.code#100

A new feature called `qenv` is being introduced with the release of teal.code.
We also implement the changes to the teal modules and framework [here](https://github.com/insightsengineering/NEST-roadmap/issues/45) and [here](https://github.com/insightsengineering/NEST-roadmap/issues/69).

We are ready to release the rest of teal packages.

### Important
Since we're releasing the modules as well, then we also have to release any affected packages that's related with `shinyvalidate` tasks [here](https://github.com/insightsengineering/NEST-roadmap/issues/57)

### Packages to be released
* teal
* teal.widgets
* teal.slice
* teal.transform
* teal.data
* tmg
* tmc (check if tern is good to go)
* goshawk + teal.goshawk
* osprey + teal.osprey
* hermes + tmhermes
* helios + tmhelios

### Order of releases
1. teal, teal.widgets, teal.slice, teal.transform, teal.data
2. tmg + tmhermes + hermes (?)
3. tmc 
4. goshawk + teal.goshawk
5. osprey + teal.osprey
6. helios + tmhelios

### Tasks
* Consult with the team to identify any obstacles or blockers preventing the releases
  * Check with Statistical Engineering (helios, hermes) and SME (tmc + tern)
* Review all packages documentation, including roxygen, examples, and vignettes, to confirm that it is up-to-date and that the code examples are functioning correctly
  * insightsengineering/teal#815
  * insightsengineering/teal.widgets#148
  * insightsengineering/teal.transform#125
  * insightsengineering/teal.slice#238
  * insightsengineering/teal.data#142
  * insightsengineering/teal.modules.general#521
  * Need to create issues for tmhelios, tmhermes, tmc upon confirmation
* run integration test (scribe) before performing each release
  * insightsengineering/idr-tasks#531
  * Need to create issues for rest of releases
* Review tests coverage, add new tests if needed (Do we need this? Up for discussion)
* Conduct testing on all sample applications available on teal.gallery
  * This can be done using the public apps URL on teal.gallery since the apps are sourced from the main branch
* Release products
  - https://github.com/insightsengineering/nestdevs-tasks/issues/24
  - More releases

**Comment by asbates** [comment]
I also recommend removing anything deprecated (e.g. chunks). I think it would be confusing for users if they install a new CRAN package and it has deprecation warnings.

**Comment by asbates** [comment]
> > Releasing teal.goshawk and teal.osprey requires release of goshawk and osprey I believe. Likewise with tmhelios I presume.
> 
> That's a valid point, and most likely true for helios. As for goshawk and osprey, I don't see if there's any impact if we don't release them. I could be wrong and could use another set of eyes. Regardless, I will add it to our plan.

teal.goshawk depends on goshawk and teal.osprey depends on osprey. So I don't see why we would release the teal packages but not the packages they depend on. I'm not even sure if CRAN allows that.

**Comment by donyunardi** [comment]
Because of these two PRs that affects update in both `teal.data` and `teal.slice`, we need to release `teal.data` as well:
https://github.com/insightsengineering/teal.data/issues/120
https://github.com/insightsengineering/teal.slice/pull/169

I will include `teal.data` in Release 1.

**Comment by donyunardi** [comment]
Due to my finding here: https://github.com/insightsengineering/idr-tasks/issues/540#issuecomment-1553992381
We have to release tmhermes after release 1.
OP updated.

**Comment by donyunardi** [comment]
Release 1 is completed.
We will move with teal modules in #25 for the next increment.
