### ISSUE TITLE
Simplify chunks (3) - wrap up qenv 

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/nestdevs-tasks#2]
Continuation of insightsengineering/NEST-roadmap/issues/69

### Items to do after `teal_refactor` is merged:
- [x] https://github.com/insightsengineering/teal.code/issues/84

### Item still needs to be refined for next development:
- [x] https://github.com/insightsengineering/teal/issues/769
- [x] https://github.com/insightsengineering/teal/issues/937

**Comment by pawelru** [comment]
This has been done
