### ISSUE TITLE
Address findings from CICD workflow update

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/nestdevs-tasks#22]
There are two update that will be done in the workflow to all NEST packages
* r-min-deps-check workflow
* fail on notes workflow
 
This issue to address any findings that comes up from the workflow update.

### Acceptance Criteria:
* Address findings from the workflow update to all repos

### Issues
* https://github.com/insightsengineering/r-verdepcheck-action/issues/4
* https://github.com/insightsengineering/idr-tasks/issues/513
* https://github.com/insightsengineering/nestdevs-tasks/issues/7

**Comment by pawelru** [comment]
this is being worked on during workflow introduction. closing as a duplicate
