### ISSUE TITLE
New filter panel UX elements design

### ISSUE THREAD

**Issue by lcd2yyz** [insightsengineering/nestdevs-tasks#27]
To do after implementation of functional element for the filter panel refactor

Comprehensive review of UX designs for the new filter panel, including but not limited to the following
- Color schemes, working with bootstrap theming
- Consistency in fonts and fontsizes
- UX behavior (eg. color highlights, mouse cursor change)
- Spatial arrangements of various UI elements (eg. margins, spacing)
- Buttons/icons

Collection of existing issues 
- [x] https://github.com/insightsengineering/teal.slice/issues/209
- [x] https://github.com/insightsengineering/teal.slice/issues/213
- [x] https://github.com/insightsengineering/teal.slice/issues/239
- [ ] https://github.com/insightsengineering/teal.slice/issues/252
- [x] https://github.com/insightsengineering/teal.slice/issues/263
- [x] https://github.com/insightsengineering/teal.slice/issues/269
- [ ] https://github.com/insightsengineering/teal/issues/802
- [x] https://github.com/insightsengineering/teal.slice/issues/320
- [ ] https://github.com/insightsengineering/teal.slice/issues/338
- [x] https://github.com/insightsengineering/teal/issues/883
- [ ] https://github.com/insightsengineering/teal.modules.general/issues/575

Update from Aug 2023
We will be getting an UX designer to conduct an UI/UX review for teal and teal modules within 2023/PI4 (Aug-Oct), so there may be more issues based on the finding from the review

**Comment by chlebowa** [comment]
[disable filter card body](https://github.com/insightsengineering/teal.slice/issues/276) is not a UX issue.

**Comment by donyunardi** [comment]
I moved the unfinished issue here to https://github.com/insightsengineering/teal/issues/1289
Closing.
