### ISSUE TITLE
Plan for teal modules release on CRAN (Part 5)

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/nestdevs-tasks#49]
Continuation of insightsengineering/nestdevs-tasks#42 

### Summary
Now that teal frameworks made it to CRAN, we are now ready to release the teal modules:
* teal.modules.general
* teal.modules.clinical 
* teal.osprey
* teal.goshawk
* teal.modules.hermes

Before we can release the modules, the following packages also has to be released in CRAN first:
* teal.transform
* osprey
* goshawk
* hermes

### Task (Priority)
* https://github.com/insightsengineering/teal.transform/issues/172
* https://github.com/insightsengineering/teal.modules.clinical/issues/919
* example app testing again?
* https://github.com/insightsengineering/teal.transform/issues/171
* https://github.com/insightsengineering/teal.modules.clinical/issues/920
 
### Still need to discuss
We decided to hold off the release of these modules packages:
1. osprey (8) (20)
    - Detected old roxygen syntax, let's use new syntax
1. teal.osprey (8) (20)
    - osprey and teal.osprey should be led by the same person 
1. goshawk (8)
1. teal.goshawk (13)
    - goshawk and teal.goshawk should be led by the same person 
1. ~~teal.modules.hermes~~

**Comment by donyunardi** [comment]
@insightsengineering/nest-core-dev 
After discussions with the ETLs and POs, we have decided to maintain teal.transform as it is for now to facilitate the release of the modules. We will proceed with the release first to alleviate future pressure and provide us with the more time when refactoring the teal.transform.

> CoreDev will review from optimize but Description will need to be populated by SME

Hi @shajoezhu 
Now that we have completed the teal.data refactor, I would like to inform you about the plan to proceed with the tmc release in the next increment. CoreDev can assist in reviewing the code (refer to [this link](https://github.com/insightsengineering/nestdevs-tasks/issues/50) for our regular pre-release checklist), but I believe SMEs should also be involved in this activity. For instance, some modules lack descriptions or details (only having a title), and a review of vignettes and NEWS.md may best be done by SME.

If you agree, I can take the initiative to create a custom pre-release checklist for tmc and delineate the responsibilities for both CoreDev and SMEs. What do you think?

**Comment by shajoezhu** [comment]
that is amazing! Thand @donyunardi ! Let's do it! If you don't create the checklist, and we can divide the work

**Comment by pawelru** [comment]
This is done!
