### ISSUE TITLE
Standardize the notation for `optional` parameters in documentation

### ISSUE THREAD

**Issue by kartikeyakirar** [insightsengineering/nestdevs-tasks#52]
In our ongoing efforts to maintain consistency across our documentation, particularly within Nest packages it has become apparent that we need to align on a standardized way to indicate `optional` parameters in our documentation. This issue arises from our discussion [here](https://github.com/insightsengineering/teal.modules.general/pull/646#discussion_r1499323682).

Currently, @averissimo identified various formats in use across different packages, as follows:

```
@param optional (character) ...
@param (optional character) ...
@param (character, optional) ...
@param (character) optional ...
```

The suggested format, based on our collective insights, is `@param (character) optional .... `

## Changes to be done  here
- [ ] teal https://github.com/insightsengineering/teal/pull/1121 
- [x] teal.data https://github.com/insightsengineering/teal.data/pull/302 reviewer: @m7pr 
- [ ] teal.code (not required)
- [x] teal.transform https://github.com/insightsengineering/teal.transform/pull/204 reviewer: @m7pr 
- [ ] teal.reporter (not required)
- [x] teal.slice https://github.com/insightsengineering/teal.slice/pull/567  reviewer: @m7pr 
- [ ] teal.widgets https://github.com/insightsengineering/teal.widgets/pull/231 reviewer: @m7pr 
- [ ] teal.logger (not required)
- [x] teal.modules.clinical https://github.com/insightsengineering/teal.modules.clinical/pull/1094  reviewer: @m7pr 
- [ ] teal.modules.general (not required)
- [ ] teal.goshawk (not required)
- [x] teal.modules.helios https://github.com/insightsengineering/teal.modules.helios/pull/122
- [ ] teal.modules.hermes (not required)
- [x] teal.osprey https://github.com/insightsengineering/teal.osprey/pull/260 reviewer: @m7pr

**Comment by m7pr** [comment]
So it's probably gonna be `@param (class) optional, ...` in most of the places

**Comment by pawelru** [comment]
Hey @kartikeyakirar. It looks like every package that requires action had been done. Can we close it?

**Comment by kartikeyakirar** [comment]
Yes
