### ISSUE TITLE
teal_transform_module

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/nestdevs-tasks#58]
These issues are relatively easy and don't introduce any breaking changes. It is a pure `teal_transform_module`.

1. https://github.com/insightsengineering/teal/issues/1229
2. https://github.com/insightsengineering/teal.slice/issues/592
3. https://github.com/insightsengineering/teal/issues/1226 (blocked by 1) @m7pr 
4. https://github.com/insightsengineering/teal/issues/1228
5. https://github.com/insightsengineering/teal/issues/1230 (blocked by 4)
6. https://github.com/insightsengineering/teal/issues/1231
7. https://github.com/insightsengineering/teal/issues/1298
8. https://github.com/insightsengineering/teal/issues/1299
9. https://github.com/insightsengineering/teal/issues/1303
10. https://github.com/insightsengineering/teal/issues/1300
11. https://github.com/insightsengineering/teal/issues/1306

PRs:
* https://github.com/insightsengineering/teal/pull/1253
* https://github.com/insightsengineering/teal.slice/pull/603

Others:
* https://github.com/insightsengineering/teal/issues/1304

**Comment by averissimo** [comment]
Should we include https://github.com/insightsengineering/teal/issues/1306 in the list above?
