### ISSUE TITLE
Reduce package(s) size

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/nestdevs-tasks#87]
Have a look at the `formatters`:

```
❯ R CMD BUILD formatters
* checking for file ‘formatters/DESCRIPTION’ ... OK
* preparing ‘formatters’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘formatters_0.5.9.9003.tar.gz’

❯ tar -tzvf formatters_0.5.9.9003.tar.gz | sort -k3 -hr
-rw-r--r--  0 ruckip staff 1847812 Dec  6  2023 formatters/man/figures/logo.png
-rw-r--r--  0 ruckip staff  925622 Nov  6  2023 formatters/data/ex_advs.rda
-rw-r--r--  0 ruckip staff  629211 Nov  6  2023 formatters/data/ex_adqs.rda
-rw-r--r--  0 ruckip staff  493724 Nov  6  2023 formatters/data/ex_adlb.rda
-rw-r--r--  0 ruckip staff   58553 Jun 10 11:05 formatters/R/pagination.R
-rw-r--r--  0 ruckip staff   58457 Nov  6  2023 formatters/data/ex_adae.rda
-rw-r--r--  0 ruckip staff   56998 Jun 10 11:05 formatters/R/tostring.R
-rw-r--r--  0 ruckip staff   50367 Nov  6  2023 formatters/data/ex_admh.rda
-rw-r--r--  0 ruckip staff   48949 Nov  6  2023 formatters/data/ex_adcm.rda
-rw-r--r--  0 ruckip staff   45794 Oct 11 10:16 formatters/R/matrix_form.R
-rw-r--r--  0 ruckip staff   43801 Nov  6  2023 formatters/data/ex_adaette.rda
-rw-r--r--  0 ruckip staff   42991 Nov  6  2023 formatters/data/ex_adrs.rda
-rw-r--r--  0 ruckip staff   42770 Nov  6  2023 formatters/data/ex_adtte.rda
-rw-r--r--  0 ruckip staff   28158 Aug 13 14:33 formatters/tests/testthat/test-formatters.R
-rw-r--r--  0 ruckip staff   25210 Nov 14 18:02 formatters/inst/doc/formatters.html
-rw-r--r--  0 ruckip staff   23892 Jun 10 11:05 formatters/R/mpf_exporters.R
(...)
```

when untared:
```
❯ total_size=$(du -sk . | awk '{print $1}')
find . -type f -exec du -sk {} + | awk -v total_size=$total_size '{printf "%s %d KB (%.2f%%)\n", $2, $1, ($1/total_size)*100}' | sort -k2,2nr
./man/figures/logo.png 1808 KB (37.05%)
./data/ex_advs.rda 904 KB (18.52%)
./data/ex_adqs.rda 616 KB (12.62%)
./data/ex_adlb.rda 484 KB (9.92%)
./R/pagination.R 60 KB (1.23%)
```

- 37% of package size is consumed by the logo alone!
- looking into the codebase of that repo - we are not using `ex_` datasets at all. But it might be used elsewhere. There are few packages that are using `ex_adlb` but I cannot find any usage of `ex_advs` and `ex_adqs`.

Adding this in general task repo to repeat the analysis for multiple packages and find a common solution.

It's important because of:
- R CMD CHECK note about size
- WebR with package downloads on the client (website user) side so we aim to have small and fast installable packages. I'm seeing two ways of doing this: limiting deps (not discussed here) and reducing the size (this issue). Currently it's neither good or bad. Have a look at the below extract from a random shinylive teal app in the tlg-catalog (devtools in chrome - network tab - open shinylive tab). This is filtered to downloaded `.tgz` files and order by size.
![image](https://github.com/user-attachments/assets/76abfa63-0ac9-4c39-a6d5-e8ea6f102121)

**Comment by llrs-roche** [comment]
Reducing the logo file size is relatively easy (using an online tool reduced the size by 70% to ~500KB). I also think that the size of the logo should be checked, as I found that for formatters is quite big 1299x1501 (compared it with teal logo at teal/man/figures/teal.png of 278x321 it is >20 times bigger).

Dimensions of the logos found: 

```
teal/man/figures/teal.png
[1] 278 321
rtables/man/figures/logo.png:
[1] 1501 1501
formatters/man/figures/logo.png:
[1] 1299 1501

> file.size("../teal/man/figures/teal.png")
[1] 79859
> file.size("../rtables/man/figures/logo.png")
[1] 1929788
> file.size("../formatters/man/figures/logo.png")
[1] 498770
```

I think that only compressing can be enough, but we should reduce the file size of the logos for rtables and formatters. 
Note also that teal and formatters' logos have the same proportion but rtables one is a square.

Checking for objects/datasets not used can be more complicated because it is harder to automate as they might be used internally or by other repositories, and I don't know a good method to automatically extract which objects are datasets from an R package (checking https://pharmaverse.r-universe.dev/datasets, reports 33 datasets from teal.* packages but it is harder to explore) .

**Comment by llrs-roche** [comment]
Logos were compressed to reduce size. After the two compressors only a third of the size was left ~500Kb.  As described above, logos have different dimension size, reducing it to the minimum would help too to avoid bloating packages.

# Manual check of datasets & usage

Go to [r-universe.dev/datasets](https://r-universe.dev/datasets) and filter by "teal." => There are 33 datasets 
11 from formatters.
Those with an x are those already reviewed. If there is no usage at all edit the line to add "No usage" or something similar.
Note, Github search is not reliable when filtering out some code ("ex_advs -tmc_ex_advs"): some results that only have `ex_advs` (as per a search with just "ex_advs") will disappear when negating `tmc_ex_advs`. 

- [x] [rADTTE](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+rADTTE+-path%3Aman&type=code) @m7pr 
- [x] [default_cdisc_join_keys](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+default_cdisc_join_keys+-path%3Aman&type=code) @m7pr 
- [x] [rADAE](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+rADAE+-path%3Aman&type=code) @m7pr 
- [x] [rADCM](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+rADCM+-path%3Aman&type=code) @m7pr 
- [x] [rADEX](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+rADEX+-path%3Aman&type=code) @m7pr 
- [x] [rADLB](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+rADLB+-path%3Aman&type=code) @m7pr 
- [x] [rADRS](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+rADRS+-path%3Aman&type=code) @m7pr 
- [x] [rADSL](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+rADSL+-path%3Aman&type=code) @m7pr 
- [x] [rADTR](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+rADTR+-path%3Aman&type=code) @m7pr 
- [x] [rADTTE](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+rADTTE+-path%3Aman&type=code) @m7pr 
- [x] [rADVS](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+rADVS+-path%3Aman&type=code) @m7pr 
- [x] [rADAE](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+rADAE+-path%3Aman&type=code) @m7pr 
- [x] [rADLB](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+rADLB+-path%3Aman&type=code) @m7pr 
- [x] [rADRS](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+rADRS+-path%3Aman&type=code) @m7pr 
- [x] [rADSL](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+rADSL+-path%3Aman&type=code) @m7pr 
- [x] [rADTTE](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+rADTTE+-path%3Aman&type=code) @m7pr 
- [x] [tmc_ex_adae](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+tmc_ex_adae+-path%3Aman&type=code) @llrs-roche 
- [x] [tmc_ex_adaette](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+tmc_ex_adaette+-path%3Aman&type=code) @llrs-roche 
- [x] [tmc_ex_adcm](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+tmc_ex_adcm+-path%3Aman&type=code) @llrs-roche 
- [x] [tmc_ex_adeg](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+tmc_ex_adeg+-path%3Aman&type=code) @llrs-roche 
- [x] [tmc_ex_adex](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+tmc_ex_adex+-path%3Aman&type=code) @llrs-roche 
- [x] [tmc_ex_adlb](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+tmc_ex_adlb+-path%3Aman&type=code) @llrs-roche 
- [x] [tmc_ex_admh](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+tmc_ex_admh+-path%3Aman&type=code) @llrs-roche 
- [x] [tmc_ex_adqs](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+tmc_ex_adqs+-path%3Aman&type=code)  @llrs-roche  No usage beyond the package
- [x] [tmc_ex_adrs](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+tmc_ex_adrs+-path%3Aman&type=code)  @llrs-roche  
- [x] [tmc_ex_adsl](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+tmc_ex_adsl+-path%3Aman&type=code)  @llrs-roche  
- [x] [tmc_ex_adtte](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+tmc_ex_adtte+-path%3Aman&type=code)  @llrs-roche  
- [x] [tmc_ex_advs](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+tmc_ex_advs+-path%3Aman&type=code):   @llrs-roche  no usage beyond 
- [x] [rADAE](https://github.com/search?q=rADAE++repo%3Ainsightsengineering%2Fteal.transform+&type=code)  @llrs-roche  Duplicated from [csdisc.random.data](https://github.com/insightsengineering/teal.modules.general/blob/46e5267951f341d7245042a1826d31406c0f2417/data-raw/data.R#L1), only used for tests  
- [x] [rADLB](https://github.com/search?q=rADLB++repo%3Ainsightsengineering%2Fteal.transform+&type=code)  @llrs-roche  Duplicated from [csdisc.random.data], only used for tests (https://github.com/insightsengineering/teal.modules.general/blob/46e5267951f341d7245042a1826d31406c0f2417/data-raw/data.R#L1)
- [x] [rADRS](https://github.com/search?q=rADLB++repo%3Ainsightsengineering%2Fteal.transform+&type=code)  @llrs-roche   Duplicated from [csdisc.random.data](https://github.com/insightsengineering/teal.modules.general/blob/46e5267951f341d7245042a1826d31406c0f2417/data-raw/data.R#L1), only used for tests
- [x] [rADSL](https://github.com/search?q=rADSL++repo%3Ainsightsengineering%2Fteal.transform+&type=code)  @llrs-roche   Duplicated from [csdisc.random.data](https://github.com/insightsengineering/teal.modules.general/blob/46e5267951f341d7245042a1826d31406c0f2417/data-raw/data.R#L1), labeled as internal but used on examples, [README](https://github.com/insightsengineering/teal.transform/blob/5a5349b45fd256865714ef2d2dd3603e45bccfbc/README.md?plain=1#L50) and vignette. 
- [x] [rADTTE](https://github.com/search?q=rADTTE++repo%3Ainsightsengineering%2Fteal.transform+&type=code)  @llrs-roche   Duplicated from [csdisc.random.data](https://github.com/insightsengineering/teal.modules.general/blob/46e5267951f341d7245042a1826d31406c0f2417/data-raw/data.R#L1), labeled as internal but used on examples, tests and vignettes
- [x] [DM](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+DM+-path%3Aman&type=code)  @llrs-roche  
- [x] [ex_adae](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+ex_adae+-path%3Aman&type=code)  @llrs-roche  
- [x] [ex_adaette](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+ex_adaette+-path%3Aman&type=code)  @llrs-roche  
- [x] [ex_adcm](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+ex_adcm+-path%3Aman&type=code)  @llrs-roche  
- [x] [ex_adlb](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+ex_adlb+-path%3Aman&type=code)  @llrs-roche  
- [x] [ex_admh](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+ex_admh+-path%3Aman&type=code)  @llrs-roche  
- [x] [ex_adqs](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+ex_adqs+-path%3Aman&type=code)  @llrs-roche  
- [x] [ex_adrs](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+ex_adrs+-path%3Aman&type=code)  @llrs-roche  
- [x] [ex_adsl](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+ex_adsl+-path%3Aman&type=code)  @llrs-roche  
- [x] [ex_adtte](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+ex_adtte+-path%3Aman&type=code)   @llrs-roche  No usage
- [x] [ex_advs](https://github.com/search?q=org%3Ainsightsengineering+OR+org%3Acran+ex_advs+-path%3Aman&type=code)   @llrs-roche  No usage (different dataset than from tmc_ex_adae?)


From the datasets name (and size) there seems to be some data duplication or reexport (for example rADTTE is in 4 different packages). One way to reduce package size would be to move all these datasets to a single data package.

**Comment by m7pr** [comment]
> From the datasets name (and size) there seems to be some data duplication or reexport (for example rADTTE is in 4 different packages). One way to reduce package size would be to move all these datasets to a single data package.

@llrs-roche in the past we had all datasets in one package, but we decided to delete this package and just move data directly to packages where the data is used. That's why you see some duplications

**Comment by m7pr** [comment]
However for cases like this, where multiple packages already depend on each other, and they all are using the same dataset we can delete rADAE from teal.modules.general and reuse this data from teal.data

<img width="893" alt="image" src="https://github.com/user-attachments/assets/56fab332-f0cd-4ab4-b3f3-025fab678618" />

**Comment by m7pr** [comment]
@llrs-roche 3 PRs where we can remove datasets becuase they all exist in teal.data already
- https://github.com/insightsengineering/teal.modules.general/pull/818
- https://github.com/insightsengineering/teal.modules.hermes/pull/396
- https://github.com/insightsengineering/teal.transform/pull/228

**Comment by pawelru** [comment]
@llrs-roche thanks for your work on this!
Would you be able to check the logos for other packages as well? E.g. [logo for `rlistings`](https://github.com/insightsengineering/rlistings/blob/main/man/figures/logo.png) is also quite big ~2MB. If we already started doing this - let's do this for all pkgs and close this topic for good.

**Comment by llrs-roche** [comment]
@pawelru there are ~[40 logos](https://github.com/search?q=org%3Ainsightsengineering%20logo.png&type=code) to deal with on the organization, and I don't have a script to automate this... 
I'll keep it in mind for next week as I want to work on https://github.com/insightsengineering/teal/issues/1323 to give time to the team to give feedback before we take holidays.

**Comment by pawelru** [comment]
Yes - that's somewhat expected. I don't think it would be ~40 - rather closer to ~20 but still quite a lot of work. I'm aware. Hopefully not all of them would require action but I just wanted do this completely and never come back to it.

**Comment by m7pr** [comment]
Alrighty, @pawelru and @llrs-roche I think we can reduce logos during https://github.com/insightsengineering/nestdevs-tasks/issues/93

And when it comes to datasets - 3 packages can be simplified and reuse data from teal.data https://github.com/insightsengineering/nestdevs-tasks/issues/87#issuecomment-2541137114

Lastly @llrs-roche I need to know your recommendations on those formatters datasets
<img width="580" alt="image" src="https://github.com/user-attachments/assets/745df3be-2056-4386-8598-c4d77a833a6c" />

**Comment by llrs-roche** [comment]
Those datasets are from formatters, and some overlap by name with those on tmc. However, between tmc and formatters there are some differences often tmc datasets have fewer rows and some have fewer columns. Sometimes a similar dataset is present on tern. formatters data is used by other packages like rlistings on the vignettes.  

There is no dependency controlled by us shared between formatters and tmc, so I wouldn't remove the data from either of them to add a new dependency from one to the other. This would complicate the installation for minimal gains.

**Comment by m7pr** [comment]
Alrighty, thanks @llrs-roche for the review. I guess we can close this issue for now?

**Comment by llrs-roche** [comment]
Yes,, we can close and keep track of the logos size on #93
